Signup and login.
Once logged in, you'll see a link called Users, which will show you a list of other users signed up for the website.
Click on an individual user and you can follow them and see their profile information. Go back to the homepage and click
the Following page to see a list of the Users who follow you and the Users that you follow.
There is also an events link on the homepage, that will take you to a list of events which you can join or leave. Go to my events
to see the events you've created as well as the ones you've joined. You also have your own profile page where you can edit what other users will see.
